# Пользователи
## Создание нового пользователя

POST http://localhost:5000/users/register/ HTTP/1.1
Content-Type: application/json

{
  "name": "Freddy Krueger",
  "email": "nightmare-on@elm.str",
  "avatar": "freddy-face.jpg",
  "userType": "Standard",
  "password": "12FreddysC4U"
}

###

## Авторизация пользователя

POST http://localhost:5000/users/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "nightmare-on@elm.str",
  "password": "12FreddysC4U"
}

###

## Отправить изображение

POST http://localhost:5000/users/65e4659bf7cb9a181de2cc70/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/iMusin/Desktop/learning-frontend/html-academy/node-js/1177121-six-cities-6/markup/img/avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
