import {
  EAmenity,
  ECity,
  EHouseType,
  EUserRole,
  TOffer,
} from '../types/index.js';

const DECIMAL_SYSTEM = 10;

export const createOffer = ([
  title,
  description,
  createdDate,
  city,
  preview,
  photos,
  isPremium,
  isFavorite,
  rating,
  houseType,
  roomsCount,
  guestsCount,
  price,
  amenities,
  name,
  email,
  avatar,
  userType,
  commentCount,
  latitude,
  longitude,
]: string[]): TOffer => ({
  title,
  description,
  postDate: new Date(createdDate),
  city: ECity[city as keyof typeof ECity],
  preview,
  photos: photos.split(';'),
  isPremium: JSON.parse(isPremium),
  isFavorite: JSON.parse(isFavorite),
  rating: Number.parseFloat(rating),
  houseType: EHouseType[houseType as keyof typeof EHouseType],
  roomsCount: Number.parseInt(roomsCount, DECIMAL_SYSTEM),
  guestsCount: Number.parseInt(guestsCount, DECIMAL_SYSTEM),
  price: Number.parseInt(price, DECIMAL_SYSTEM),
  amenities: amenities.split(';').map((amenity) => amenity as EAmenity),
  user: {
    name,
    email,
    avatar,
    userType: EUserRole[userType as keyof typeof EUserRole],
  },
  commentCount: Number.parseInt(commentCount, DECIMAL_SYSTEM),
  location: {
    latitude: Number.parseFloat(latitude),
    longitude: Number.parseFloat(longitude),
  },
});
